[package]
name = "consoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.71"
rust-bert = "0.21.0"
tch = "0.13.0"
inquire = "0.6.2"
reqwest = { version = "0.11.18", features = ['json']}
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls"] }
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.97"
tmux_interface = "0.3.0"
tokio = { version = "1.28.2", features = ["full"] }

