language_model:
  # default_model: "gpt-3.5-turbo-0613"
  api_key: "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"

database:
  host: 127.0.0.1
  port: 5432
  username: "voidkandy"
  password: "strawhat.jury.steamboat.mother"
  database_name: "espionox"
